sonar.projectKey=MiAppNetCore
sonar.working.directory=C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp
sonar.pullrequest.cache.basepath=C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp

C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.projectKey=MiAppNetCore:C0694E6B-E884-45E4-817E-C8A238B7019B
C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.projectName=VulnerableApp
C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.projectBaseDir=C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp
C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.sourceEncoding=utf-8
C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.tests=
C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.sources=\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Controllers\\ApiController.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Controllers\\AuthController.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Controllers\\CommentController.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Controllers\\HomeController.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Controllers\\SearchController.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Data\\AppDbContext.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Migrations\\20260606045559_SecureDb.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Migrations\\20260606045559_SecureDb.Designer.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Migrations\\AppDbContextModelSnapshot.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Models\\ErrorViewModel.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Models\\User.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Program.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\VulnerableApp.GlobalUsings.g.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\VulnerableApp.AssemblyInfo.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\VulnerableApp.RazorAssemblyInfo.cs",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\css\\site.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\favicon.ico",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\js\\site.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.min.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.min.css.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.js.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.min.js.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.js.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.min.js.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.js.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.min.js.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\bootstrap\\LICENSE",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation-unobtrusive\\dist\\jquery.validate.unobtrusive.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation-unobtrusive\\dist\\jquery.validate.unobtrusive.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation-unobtrusive\\LICENSE.txt",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation\\dist\\additional-methods.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation\\dist\\additional-methods.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation\\dist\\jquery.validate.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation\\dist\\jquery.validate.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery-validation\\LICENSE.md",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery\\dist\\jquery.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery\\dist\\jquery.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery\\dist\\jquery.min.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery\\dist\\jquery.slim.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery\\dist\\jquery.slim.min.js",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery\\dist\\jquery.slim.min.map",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\wwwroot\\lib\\jquery\\LICENSE.txt",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\appsettings.Development.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\appsettings.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Auth\\Dashboard.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Auth\\Login.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Comment\\Index.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Home\\Index.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Home\\Privacy.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Search\\Index.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Shared\\Error.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Shared\\_Layout.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Shared\\_ValidationScriptsPartial.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\_ViewImports.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\_ViewStart.cshtml",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Views\\Shared\\_Layout.cshtml.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\README.md",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\Properties\\launchSettings.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\project.assets.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\VulnerableApp.csproj.nuget.dgspec.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\VulnerableApp.deps.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\VulnerableApp.runtimeconfig.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\VulnerableApp.staticwebassets.endpoints.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\VulnerableApp.staticwebassets.runtime.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\rbcswa.dswa.cache.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\rjimswa.dswa.cache.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\staticwebassets.development.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\VulnerableApp.sourcelink.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\BuildHost-net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\scopedcss\\bundle\\VulnerableApp.styles.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\scopedcss\\projectbundle\\VulnerableApp.bundle.scp.css",\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\obj\\Debug\\net10.0\\scopedcss\\Views\\Shared\\_Layout.cshtml.rz.scp.css"

C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\.sonarqube\\out\\0"
C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\.sonarqube\\out\\0\\Issues.json"
C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.cs.scanner.telemetry=\
"C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\.sonarqube\\out\\0\\Telemetry.json"

C0694E6B-E884-45E4-817E-C8A238B7019B.sonar.working.directory=C:\\Users\\Andyy\\OneDrive\\Documentos\\SDA_8vo\\practicas\\vulnerableapp\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=C0694E6B-E884-45E4-817E-C8A238B7019B

